### ISSUE TITLE
User Research and Report

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#18]

**Comment by Abasiye** [comment]
User research was carried out by me and few other team members and it has been fully documented

**Comment by Hardexa** [comment]
https://docs.google.com/document/d/1vg0zJd0SHATPbeOahuH7iq1cDXOwnksl-KSDbise2F8/edit?usp=sharing
I and the rest of Designers in the team worked on User Research Report except  Mbonu Glory

**Comment by Shally2luv** [comment]
I and other team members worked In user research.


https://docs.google.com/document/d/1vg0zJd0SHATPbeOahuH7iq1cDXOwnksl-KSDbise2F8/edit?usp=drivesdk
