### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#30]

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=550%3A2918
I was issued Home page design

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=273%3A652
Homepage
