### ISSUE TITLE
Password Reset Page Design

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#31]

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=550%3A2918
I was issued Reset password page

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=2%3A3
password reset page
