### ISSUE TITLE
Design Style Guide

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#32]

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=550%3A2918
I was issued style guide

**Comment by Shally2luv** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=2%3A3

I worked on style guide with the team

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=0%3A1
Style guide
