### ISSUE TITLE
User Page Pop up

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#33]

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=550%3A2918
I was issued user page pop up

**Comment by Hardexa** [comment]
https://www.figma.com/file/oUI3wf2x5ZLns4Y6TR9q5W/CC-GENERATOR-(Copy)?node-id=273%3A2648
user page pop
