### ISSUE TITLE
Complete Design Folder

### ISSUE THREAD

**Issue by MideMario** [zuri-training/CC-Generator-Team122#4]
Each design team member should comment on their contribution to the design process with the link to their file.

**Comment by Abasiye** [comment]
I was tasked with designing the "Login and Sign Up Page, Contact and About Us Page, User Profile and Settings Page" and the figma link will be provided.

**Comment by Phebian7** [comment]
Libraries / Categories / Card Holding web page design was assigned to me. At the moment; Card libraries / categories have been designed, while the card holding page will be updated anytime soon. I will drop the link soon too.

**Comment by Shally2luv** [comment]
I am to work on the mobile responsive page for : Main Page, Landing Page, Sign In Page, Sign Up Page and Contact Us Page. 

At the moment All are ready.

**Comment by Kendrick02** [comment]
I was tasked with designing the mobile screens for cards libraries/categories/ card holding pages. Here's the figma link:
https://www.figma.com/file/hc6YUG0N1UuHpq0kprkge2/Mobile-cards-library%2Fcategories%2Fholding-page?node-id=45%3A599

**Comment by Bayilasolomon** [comment]
I was tasked with creating a Profile page, about us, and profile settings - for mobile responsive
Here's the link
